USER_DANCING_BRACKETS_ENABLE = no
USER_BACKLIGHT_ENABLE = no
USER_CAPS_WORD_ENABLE = yes
USER_DOUBLE_SPACE_SENTENCE_ENABLE = yes

# Explicitly disable all not used features to reduce size.
BOOTMAGIC_ENABLE = no
MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = no
CONSOLE_ENABLE = yes
COMMAND_ENABLE = no
COMBO_ENABLE = yes
NKRO_ENABLE = no
AUDIO_ENABLE = no
RGBLIGHT_ENABLE = no
LEADER_ENABLE = no
LTO_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes
